name: posterr
description: The new way to do networking.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  provider: ^6.0.3
  rxdart: ^0.27.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
